// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TAREATOPICOS.ServicioA.Data;

#nullable disable

namespace ServicioA.Migrations
{
    [DbContext(typeof(ServicioAContext))]
    [Migration("20250822214754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Creditos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creditos = 0,
                            Nombre = "Matemáticas I"
                        },
                        new
                        {
                            Id = 2,
                            Creditos = 0,
                            Nombre = "Programación I"
                        },
                        new
                        {
                            Id = 3,
                            Creditos = 0,
                            Nombre = "Bases de Datos"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlanesEstudio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2025,
                            Nombre = "Ingeniería de Sistemas"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PlanId", "MateriaId")
                        .IsUnique();

                    b.ToTable("PlanMaterias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MateriaId = 1,
                            PlanId = 1,
                            Semestre = 1
                        },
                        new
                        {
                            Id = 2,
                            MateriaId = 2,
                            PlanId = 1,
                            Semestre = 1
                        },
                        new
                        {
                            Id = 3,
                            MateriaId = 3,
                            PlanId = 1,
                            Semestre = 2
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanMateria", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.Materia", "Materia")
                        .WithMany("PlanMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAREATOPICOS.ServicioA.Models.PlanEstudio", "Plan")
                        .WithMany("PlanMaterias")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Materia", b =>
                {
                    b.Navigation("PlanMaterias");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanEstudio", b =>
                {
                    b.Navigation("PlanMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
