// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TAREATOPICOS.ServicioA.Data;

#nullable disable

namespace ServicioA.Migrations
{
    [DbContext(typeof(ServicioAContext))]
    partial class ServicioAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Aulas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 40,
                            Codigo = "A101",
                            Ubicacion = "Bloque A"
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 35,
                            Codigo = "B201",
                            Ubicacion = "Bloque B"
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 50,
                            Codigo = "C301",
                            Ubicacion = "Bloque C"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ingeniería de Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ingeniería Industrial"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Administración de Empresas"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.DetalleInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GrupoMateriaId")
                        .HasColumnType("integer");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<int?>("NotaFinal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMateriaId");

                    b.HasIndex("InscripcionId", "GrupoMateriaId")
                        .IsUnique();

                    b.ToTable("DetallesInscripciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "DET001",
                            Estado = "INSCRITO",
                            GrupoMateriaId = 1,
                            InscripcionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "DET002",
                            Estado = "INSCRITO",
                            GrupoMateriaId = 2,
                            InscripcionId = 2
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Docentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ci = "123456",
                            Estado = "ACTIVO",
                            Nombre = "ABARCA SOTA NANCY",
                            Registro = "DOC001",
                            Telefono = "70000001"
                        },
                        new
                        {
                            Id = 2,
                            Ci = "123457",
                            Estado = "ACTIVO",
                            Nombre = "ACOSTA CABEZAS BARTOLO JAVIER",
                            Registro = "DOC002",
                            Telefono = "70000002"
                        },
                        new
                        {
                            Id = 3,
                            Ci = "123458",
                            Estado = "ACTIVO",
                            Nombre = "AGUILAR MARTINEZ DOMINGO",
                            Registro = "DOC003",
                            Telefono = "70000003"
                        },
                        new
                        {
                            Id = 4,
                            Ci = "123459",
                            Estado = "ACTIVO",
                            Nombre = "ALIAGA HOWARD SHARON KENNY",
                            Registro = "DOC004",
                            Telefono = "70000004"
                        },
                        new
                        {
                            Id = 5,
                            Ci = "123460",
                            Estado = "ACTIVO",
                            Nombre = "ALPIRE RIVERO GERMAN",
                            Registro = "DOC005",
                            Telefono = "70000005"
                        },
                        new
                        {
                            Id = 6,
                            Ci = "123461",
                            Estado = "ACTIVO",
                            Nombre = "ARANIBAR QUIROZ M. MONICA",
                            Registro = "DOC006",
                            Telefono = "70000006"
                        },
                        new
                        {
                            Id = 7,
                            Ci = "123462",
                            Estado = "ACTIVO",
                            Nombre = "ARGOTE CLAROS IRMA ISABEL",
                            Registro = "DOC007",
                            Telefono = "70000007"
                        },
                        new
                        {
                            Id = 8,
                            Ci = "123463",
                            Estado = "ACTIVO",
                            Nombre = "ATILA LIJERON JHONNY DAVID",
                            Registro = "DOC008",
                            Telefono = "70000008"
                        },
                        new
                        {
                            Id = 9,
                            Ci = "123464",
                            Estado = "ACTIVO",
                            Nombre = "AVENDAÑO GONZALES EUDAL",
                            Registro = "DOC009",
                            Telefono = "70000009"
                        },
                        new
                        {
                            Id = 10,
                            Ci = "123465",
                            Estado = "ACTIVO",
                            Nombre = "BALCAZAR VEIZAGA EVANS",
                            Registro = "DOC010",
                            Telefono = "70000010"
                        },
                        new
                        {
                            Id = 11,
                            Ci = "123466",
                            Estado = "ACTIVO",
                            Nombre = "BARROSO VIRUEZ GINO",
                            Registro = "DOC011",
                            Telefono = "70000011"
                        },
                        new
                        {
                            Id = 12,
                            Ci = "123467",
                            Estado = "ACTIVO",
                            Nombre = "CABALLERO RUA MAURICIO CHRISTI",
                            Registro = "DOC012",
                            Telefono = "70000012"
                        },
                        new
                        {
                            Id = 13,
                            Ci = "123468",
                            Estado = "ACTIVO",
                            Nombre = "CABELLO MERIDA JUAN RUBEN",
                            Registro = "DOC013",
                            Telefono = "70000013"
                        },
                        new
                        {
                            Id = 14,
                            Ci = "123469",
                            Estado = "ACTIVO",
                            Nombre = "CACERES CHACON BRAULIO",
                            Registro = "DOC014",
                            Telefono = "70000014"
                        },
                        new
                        {
                            Id = 15,
                            Ci = "123470",
                            Estado = "ACTIVO",
                            Nombre = "CALDERON FLORES MODESTO FRANK",
                            Registro = "DOC015",
                            Telefono = "70000015"
                        },
                        new
                        {
                            Id = 16,
                            Ci = "123471",
                            Estado = "ACTIVO",
                            Nombre = "CALIZAYA AJHUACHO MAGNO EDWIN",
                            Registro = "DOC016",
                            Telefono = "70000016"
                        },
                        new
                        {
                            Id = 17,
                            Ci = "123472",
                            Estado = "ACTIVO",
                            Nombre = "CALLE TERRAZAS EDWIN",
                            Registro = "DOC017",
                            Telefono = "70000017"
                        },
                        new
                        {
                            Id = 18,
                            Ci = "123473",
                            Estado = "ACTIVO",
                            Nombre = "CAMPOS BARRERA MARIO",
                            Registro = "DOC018",
                            Telefono = "70000018"
                        },
                        new
                        {
                            Id = 19,
                            Ci = "123474",
                            Estado = "ACTIVO",
                            Nombre = "CANO CESPEDES JORGE",
                            Registro = "DOC019",
                            Telefono = "70000019"
                        },
                        new
                        {
                            Id = 20,
                            Ci = "123475",
                            Estado = "ACTIVO",
                            Nombre = "CARVAJAL CORDERO MARCIO",
                            Registro = "DOC020",
                            Telefono = "70000020"
                        },
                        new
                        {
                            Id = 21,
                            Ci = "123476",
                            Estado = "ACTIVO",
                            Nombre = "CARRENO PEREIRA ANDRES",
                            Registro = "DOC021",
                            Telefono = "70000021"
                        },
                        new
                        {
                            Id = 22,
                            Ci = "123477",
                            Estado = "ACTIVO",
                            Nombre = "CASTRO MARISCAL JHONNY",
                            Registro = "DOC022",
                            Telefono = "70000022"
                        },
                        new
                        {
                            Id = 23,
                            Ci = "123478",
                            Estado = "ACTIVO",
                            Nombre = "CAYOJA LUCANA VICTOR MILTON",
                            Registro = "DOC023",
                            Telefono = "70000023"
                        },
                        new
                        {
                            Id = 24,
                            Ci = "123479",
                            Estado = "ACTIVO",
                            Nombre = "CHAHIN AVICHACRA JUAN MANUEL",
                            Registro = "DOC024",
                            Telefono = "70000024"
                        },
                        new
                        {
                            Id = 25,
                            Ci = "123480",
                            Estado = "ACTIVO",
                            Nombre = "CHAU WONG JORGE",
                            Registro = "DOC025",
                            Telefono = "70000025"
                        },
                        new
                        {
                            Id = 26,
                            Ci = "123481",
                            Estado = "ACTIVO",
                            Nombre = "CLAURE MEDRANO DE OROPEZA ELIZ",
                            Registro = "DOC026",
                            Telefono = "70000026"
                        },
                        new
                        {
                            Id = 27,
                            Ci = "123482",
                            Estado = "ACTIVO",
                            Nombre = "CONTRERAS VILLEGAS JUAN CARLOS",
                            Registro = "DOC027",
                            Telefono = "70000027"
                        },
                        new
                        {
                            Id = 28,
                            Ci = "123483",
                            Estado = "ACTIVO",
                            Nombre = "CORTEZ UZEDA JULIO MARTIN",
                            Registro = "DOC028",
                            Telefono = "70000028"
                        },
                        new
                        {
                            Id = 29,
                            Ci = "123484",
                            Estado = "ACTIVO",
                            Nombre = "DAVALOS SANCHEZ DE MANCILLA Pl",
                            Registro = "DOC029",
                            Telefono = "70000029"
                        },
                        new
                        {
                            Id = 30,
                            Ci = "123485",
                            Estado = "ACTIVO",
                            Nombre = "DURAN CESPEDES BERTHY RONALD",
                            Registro = "DOC030",
                            Telefono = "70000030"
                        },
                        new
                        {
                            Id = 31,
                            Ci = "123486",
                            Estado = "ACTIVO",
                            Nombre = "EVELYN VANESA SORIA AVILA",
                            Registro = "DOC031",
                            Telefono = "70000031"
                        },
                        new
                        {
                            Id = 32,
                            Ci = "123487",
                            Estado = "ACTIVO",
                            Nombre = "FLORES CUELLAD DAVID LUIS",
                            Registro = "DOC032",
                            Telefono = "70000032"
                        },
                        new
                        {
                            Id = 33,
                            Ci = "123488",
                            Estado = "ACTIVO",
                            Nombre = "FLORES FLORES MARCOS OSCAR",
                            Registro = "DOC033",
                            Telefono = "70000033"
                        },
                        new
                        {
                            Id = 34,
                            Ci = "123489",
                            Estado = "ACTIVO",
                            Nombre = "FLORES GUZMAN VALENTIN VICTOR",
                            Registro = "DOC034",
                            Telefono = "70000034"
                        },
                        new
                        {
                            Id = 35,
                            Ci = "123490",
                            Estado = "ACTIVO",
                            Nombre = "GARZON CUELLAR ANGELICA",
                            Registro = "DOC035",
                            Telefono = "70000035"
                        },
                        new
                        {
                            Id = 36,
                            Ci = "123491",
                            Estado = "ACTIVO",
                            Nombre = "GIANELLA PEREDO EDUARDO",
                            Registro = "DOC036",
                            Telefono = "70000036"
                        },
                        new
                        {
                            Id = 37,
                            Ci = "123492",
                            Estado = "ACTIVO",
                            Nombre = "GIANELLA PEREDO LUIS ANTONIO",
                            Registro = "DOC037",
                            Telefono = "70000037"
                        },
                        new
                        {
                            Id = 38,
                            Ci = "123493",
                            Estado = "ACTIVO",
                            Nombre = "GONZALES SANDOVAL JORGE ANTONI",
                            Registro = "DOC038",
                            Telefono = "70000038"
                        },
                        new
                        {
                            Id = 39,
                            Ci = "123494",
                            Estado = "ACTIVO",
                            Nombre = "GRAGEDA ESCUDERO MARIO WILSON",
                            Registro = "DOC039",
                            Telefono = "70000039"
                        },
                        new
                        {
                            Id = 40,
                            Ci = "123495",
                            Estado = "ACTIVO",
                            Nombre = "GRIMALDO BRAVO PAUL",
                            Registro = "DOC040",
                            Telefono = "70000040"
                        },
                        new
                        {
                            Id = 41,
                            Ci = "123496",
                            Estado = "ACTIVO",
                            Nombre = "GUARACHI SOLANO JONATHAN FELIX",
                            Registro = "DOC041",
                            Telefono = "70000041"
                        },
                        new
                        {
                            Id = 42,
                            Ci = "123497",
                            Estado = "ACTIVO",
                            Nombre = "GUTHRIE PACHECO MIGUEL ANGEL",
                            Registro = "DOC042",
                            Telefono = "70000042"
                        },
                        new
                        {
                            Id = 43,
                            Ci = "123498",
                            Estado = "ACTIVO",
                            Nombre = "GUTIERREZ BRUNO KATIME ESTHER",
                            Registro = "DOC043",
                            Telefono = "70000043"
                        },
                        new
                        {
                            Id = 44,
                            Ci = "123499",
                            Estado = "ACTIVO",
                            Nombre = "HINOJOSA SAAVEDRA JOSE SAID",
                            Registro = "DOC044",
                            Telefono = "70000044"
                        },
                        new
                        {
                            Id = 45,
                            Ci = "123500",
                            Estado = "ACTIVO",
                            Nombre = "JUSTINIANO FLORES CARMEN LILIA",
                            Registro = "DOC045",
                            Telefono = "70000045"
                        },
                        new
                        {
                            Id = 46,
                            Ci = "123501",
                            Estado = "ACTIVO",
                            Nombre = "JUSTINIANO ROCA RONALD",
                            Registro = "DOC046",
                            Telefono = "70000046"
                        },
                        new
                        {
                            Id = 47,
                            Ci = "123502",
                            Estado = "ACTIVO",
                            Nombre = "JUSTINIANO VACA JUAN TOMAS",
                            Registro = "DOC047",
                            Telefono = "70000047"
                        },
                        new
                        {
                            Id = 48,
                            Ci = "123503",
                            Estado = "ACTIVO",
                            Nombre = "LAMAS RODRIGUEZ MARCOS",
                            Registro = "DOC048",
                            Telefono = "70000048"
                        },
                        new
                        {
                            Id = 49,
                            Ci = "123504",
                            Estado = "ACTIVO",
                            Nombre = "LAZO ARTEAGA CARLOS ROBERTO",
                            Registro = "DOC049",
                            Telefono = "70000049"
                        },
                        new
                        {
                            Id = 50,
                            Ci = "123505",
                            Estado = "ACTIVO",
                            Nombre = "LAZO QUISPE SEBASTIAN",
                            Registro = "DOC050",
                            Telefono = "70000050"
                        },
                        new
                        {
                            Id = 51,
                            Ci = "123506",
                            Estado = "ACTIVO",
                            Nombre = "LOBO LIMPIAS VICTOR HUGO",
                            Registro = "DOC051",
                            Telefono = "70000051"
                        },
                        new
                        {
                            Id = 52,
                            Ci = "123507",
                            Estado = "ACTIVO",
                            Nombre = "LOPEZ NEGRETTY MARY DUNNIA",
                            Registro = "DOC052",
                            Telefono = "70000052"
                        },
                        new
                        {
                            Id = 53,
                            Ci = "123508",
                            Estado = "ACTIVO",
                            Nombre = "LOPEZ WINNIPEG MARIO MILTON",
                            Registro = "DOC053",
                            Telefono = "70000053"
                        },
                        new
                        {
                            Id = 54,
                            Ci = "123509",
                            Estado = "ACTIVO",
                            Nombre = "MARTINEZ CANEDO ROLANDO ANTONI",
                            Registro = "DOC054",
                            Telefono = "70000054"
                        },
                        new
                        {
                            Id = 55,
                            Ci = "123510",
                            Estado = "ACTIVO",
                            Nombre = "MARTINEZ CARDONA SARAH MIRNA",
                            Registro = "DOC055",
                            Telefono = "70000055"
                        },
                        new
                        {
                            Id = 56,
                            Ci = "123511",
                            Estado = "ACTIVO",
                            Nombre = "MIRANDA CARRASCO CARLOS",
                            Registro = "DOC056",
                            Telefono = "70000056"
                        },
                        new
                        {
                            Id = 57,
                            Ci = "123512",
                            Estado = "ACTIVO",
                            Nombre = "MOLLO MAMANI ALBERTO",
                            Registro = "DOC057",
                            Telefono = "70000057"
                        },
                        new
                        {
                            Id = 58,
                            Ci = "123513",
                            Estado = "ACTIVO",
                            Nombre = "MONRROY DIPP VICTOR FERNANDO",
                            Registro = "DOC058",
                            Telefono = "70000058"
                        },
                        new
                        {
                            Id = 59,
                            Ci = "123514",
                            Estado = "ACTIVO",
                            Nombre = "MORALES MENDEZ MAGALY",
                            Registro = "DOC059",
                            Telefono = "70000059"
                        },
                        new
                        {
                            Id = 60,
                            Ci = "123515",
                            Estado = "ACTIVO",
                            Nombre = "MORENO SUAREZ ENRIQUE",
                            Registro = "DOC060",
                            Telefono = "70000060"
                        },
                        new
                        {
                            Id = 61,
                            Ci = "123516",
                            Estado = "ACTIVO",
                            Nombre = "OQUENDO HEREDIA FREDDY MIGUEL",
                            Registro = "DOC061",
                            Telefono = "70000061"
                        },
                        new
                        {
                            Id = 62,
                            Ci = "123517",
                            Estado = "ACTIVO",
                            Nombre = "ORNOSCO GOMEZ RUBEN",
                            Registro = "DOC062",
                            Telefono = "70000062"
                        },
                        new
                        {
                            Id = 63,
                            Ci = "123518",
                            Estado = "ACTIVO",
                            Nombre = "ORTIZ ARTEAGA VICTOR HUGO",
                            Registro = "DOC063",
                            Telefono = "70000063"
                        },
                        new
                        {
                            Id = 64,
                            Ci = "123519",
                            Estado = "ACTIVO",
                            Nombre = "OROPEZA CLAURE GUSTAVO ADOLFO",
                            Registro = "DOC064",
                            Telefono = "70000064"
                        },
                        new
                        {
                            Id = 65,
                            Ci = "123520",
                            Estado = "ACTIVO",
                            Nombre = "PEINADO PEREIRA JUAN CARLOS",
                            Registro = "DOC065",
                            Telefono = "70000065"
                        },
                        new
                        {
                            Id = 66,
                            Ci = "123521",
                            Estado = "ACTIVO",
                            Nombre = "PEINADO PEREIRA MIGUEL JESUS",
                            Registro = "DOC066",
                            Telefono = "70000066"
                        },
                        new
                        {
                            Id = 67,
                            Ci = "123522",
                            Estado = "ACTIVO",
                            Nombre = "PEREZ DELGADILLO SHIRLEY EULAL",
                            Registro = "DOC067",
                            Telefono = "70000067"
                        },
                        new
                        {
                            Id = 68,
                            Ci = "123523",
                            Estado = "ACTIVO",
                            Nombre = "PEREZ FERREIRA UBALDO",
                            Registro = "DOC068",
                            Telefono = "70000068"
                        },
                        new
                        {
                            Id = 69,
                            Ci = "123524",
                            Estado = "ACTIVO",
                            Nombre = "PINTO VARGAS EDUARDO",
                            Registro = "DOC069",
                            Telefono = "70000069"
                        },
                        new
                        {
                            Id = 70,
                            Ci = "123525",
                            Estado = "ACTIVO",
                            Nombre = "POR DESIGNAR",
                            Registro = "DOC070",
                            Telefono = "70000070"
                        },
                        new
                        {
                            Id = 71,
                            Ci = "123526",
                            Estado = "ACTIVO",
                            Nombre = "RISSIOTTI VELASQUEZ EDGAR ZACA",
                            Registro = "DOC071",
                            Telefono = "70000071"
                        },
                        new
                        {
                            Id = 72,
                            Ci = "123527",
                            Estado = "ACTIVO",
                            Nombre = "ROCHA ARGOTE FERNANDO",
                            Registro = "DOC072",
                            Telefono = "70000072"
                        },
                        new
                        {
                            Id = 73,
                            Ci = "123528",
                            Estado = "ACTIVO",
                            Nombre = "ROMAN ROCA RUFINO WILBERTO",
                            Registro = "DOC073",
                            Telefono = "70000073"
                        },
                        new
                        {
                            Id = 74,
                            Ci = "123529",
                            Estado = "ACTIVO",
                            Nombre = "ROSALES FUENTES JORGE MARCELO",
                            Registro = "DOC074",
                            Telefono = "70000074"
                        },
                        new
                        {
                            Id = 75,
                            Ci = "123530",
                            Estado = "ACTIVO",
                            Nombre = "SALVATIERRA MERCADO ROLANDO",
                            Registro = "DOC075",
                            Telefono = "70000075"
                        },
                        new
                        {
                            Id = 76,
                            Ci = "123531",
                            Estado = "ACTIVO",
                            Nombre = "SANCHEZ RIOJA EDWIN ALEJANDRO",
                            Registro = "DOC076",
                            Telefono = "70000076"
                        },
                        new
                        {
                            Id = 77,
                            Ci = "123532",
                            Estado = "ACTIVO",
                            Nombre = "SANCHEZ VELASCO ENRIQUE",
                            Registro = "DOC077",
                            Telefono = "70000077"
                        },
                        new
                        {
                            Id = 78,
                            Ci = "123533",
                            Estado = "ACTIVO",
                            Nombre = "SELAYA GARVIZU IVAN VLADISHLAV",
                            Registro = "DOC078",
                            Telefono = "70000078"
                        },
                        new
                        {
                            Id = 79,
                            Ci = "123534",
                            Estado = "ACTIVO",
                            Nombre = "SEVERICHE TOLEDO SAUL",
                            Registro = "DOC079",
                            Telefono = "70000079"
                        },
                        new
                        {
                            Id = 80,
                            Ci = "123535",
                            Estado = "ACTIVO",
                            Nombre = "SILES MUÑOZ FELIX",
                            Registro = "DOC080",
                            Telefono = "70000080"
                        },
                        new
                        {
                            Id = 81,
                            Ci = "123536",
                            Estado = "ACTIVO",
                            Nombre = "SUAREZ CESPEDES MELBY",
                            Registro = "DOC081",
                            Telefono = "70000081"
                        },
                        new
                        {
                            Id = 82,
                            Ci = "123537",
                            Estado = "ACTIVO",
                            Nombre = "TAPIA FLORES LUIS PERCY",
                            Registro = "DOC082",
                            Telefono = "70000082"
                        },
                        new
                        {
                            Id = 83,
                            Ci = "123538",
                            Estado = "ACTIVO",
                            Nombre = "TEJERINA GUERRA JULIO",
                            Registro = "DOC083",
                            Telefono = "70000083"
                        },
                        new
                        {
                            Id = 84,
                            Ci = "123539",
                            Estado = "ACTIVO",
                            Nombre = "TERRAZAS SOTO RICARDO",
                            Registro = "DOC084",
                            Telefono = "70000084"
                        },
                        new
                        {
                            Id = 85,
                            Ci = "123540",
                            Estado = "ACTIVO",
                            Nombre = "TORREZ CAMACHO LUZ DIANA",
                            Registro = "DOC085",
                            Telefono = "70000085"
                        },
                        new
                        {
                            Id = 86,
                            Ci = "123541",
                            Estado = "ACTIVO",
                            Nombre = "VACA PINTO CESPEDES ROBERTO CA",
                            Registro = "DOC086",
                            Telefono = "70000086"
                        },
                        new
                        {
                            Id = 87,
                            Ci = "123542",
                            Estado = "ACTIVO",
                            Nombre = "VALDELOMAR ORELLANA TOMAS",
                            Registro = "DOC087",
                            Telefono = "70000087"
                        },
                        new
                        {
                            Id = 88,
                            Ci = "123543",
                            Estado = "ACTIVO",
                            Nombre = "VALLET VALLET CORRADO",
                            Registro = "DOC088",
                            Telefono = "70000088"
                        },
                        new
                        {
                            Id = 89,
                            Ci = "123544",
                            Estado = "ACTIVO",
                            Nombre = "VARGAS CASTILLO CIRO EDGAR",
                            Registro = "DOC089",
                            Telefono = "70000089"
                        },
                        new
                        {
                            Id = 90,
                            Ci = "123545",
                            Estado = "ACTIVO",
                            Nombre = "VARGAS PEÑA LEONARDO",
                            Registro = "DOC090",
                            Telefono = "70000090"
                        },
                        new
                        {
                            Id = 91,
                            Ci = "123546",
                            Estado = "ACTIVO",
                            Nombre = "VARGAS YAPURA EDWIN",
                            Registro = "DOC091",
                            Telefono = "70000091"
                        },
                        new
                        {
                            Id = 92,
                            Ci = "123547",
                            Estado = "ACTIVO",
                            Nombre = "VEIZAGA GONZALES JOSUE OBED",
                            Registro = "DOC092",
                            Telefono = "70000092"
                        },
                        new
                        {
                            Id = 93,
                            Ci = "123548",
                            Estado = "ACTIVO",
                            Nombre = "VELASCO GUAMAN ANGEL",
                            Registro = "DOC093",
                            Telefono = "70000093"
                        },
                        new
                        {
                            Id = 94,
                            Ci = "123549",
                            Estado = "ACTIVO",
                            Nombre = "VILLAGOMEZ MELGAR JOSE JUNIOR",
                            Registro = "DOC094",
                            Telefono = "70000094"
                        },
                        new
                        {
                            Id = 95,
                            Ci = "123550",
                            Estado = "ACTIVO",
                            Nombre = "ZEBALLOS PAREDES DANIEL LUIS",
                            Registro = "DOC095",
                            Telefono = "70000095"
                        },
                        new
                        {
                            Id = 96,
                            Ci = "123551",
                            Estado = "ACTIVO",
                            Nombre = "ZUNA VILLAGOMEZ JULIO",
                            Registro = "DOC096",
                            Telefono = "70000096"
                        },
                        new
                        {
                            Id = 97,
                            Ci = "123552",
                            Estado = "ACTIVO",
                            Nombre = "ZUNA VILLAGOMEZ RICARDO",
                            Registro = "DOC097",
                            Telefono = "70000097"
                        },
                        new
                        {
                            Id = 98,
                            Ci = "123553",
                            Estado = "ACTIVO",
                            Nombre = "ZUÑIGA RUIZ WILMA",
                            Registro = "DOC098",
                            Telefono = "70000098"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            Ci = "7894561",
                            Email = "carlos@uni.edu",
                            Estado = "ACTIVO",
                            Nombre = "Carlos Sánchez",
                            PasswordHash = "$2a$11$YP4gNElOt/d79qZIHbwT3eAxgSg8R.DkDofhZOnq2dH1/IytjKdSq",
                            Registro = "20251234"
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 2,
                            Ci = "222222",
                            Email = "ana@uni.edu",
                            Estado = "ACTIVO",
                            Nombre = "Ana Rodríguez",
                            PasswordHash = "$2a$11$YP4gNElOt/d79qZIHbwT3eAxgSg8R.DkDofhZOnq2dH1/IytjKdSq",
                            Registro = "EST002"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.GrupoMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AulaId")
                        .HasColumnType("integer");

                    b.Property<int>("Cupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HorarioId")
                        .HasColumnType("integer");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("GruposMaterias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AulaId = 1,
                            Cupo = 40,
                            DocenteId = 1,
                            Estado = "ACTIVO",
                            Grupo = "A",
                            HorarioId = 1,
                            MateriaId = 1,
                            PeriodoId = 1
                        },
                        new
                        {
                            Id = 2,
                            AulaId = 2,
                            Cupo = 35,
                            DocenteId = 2,
                            Estado = "ACTIVO",
                            Grupo = "B",
                            HorarioId = 2,
                            MateriaId = 2,
                            PeriodoId = 1
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.HistorialAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("boolean");

                    b.Property<int>("DetalleInscripcionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Intento")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UltimaNota")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DetalleInscripcionId")
                        .IsUnique();

                    b.ToTable("HistorialesAcademicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aprobado = true,
                            DetalleInscripcionId = 1,
                            FechaAprobacion = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intento = 1,
                            UltimaNota = 85m
                        },
                        new
                        {
                            Id = 2,
                            Aprobado = false,
                            DetalleInscripcionId = 2,
                            FechaAprobacion = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intento = 1,
                            UltimaNota = 70m
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("Horarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dia = "Lunes",
                            HoraFin = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Dia = "Martes",
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("Inscripciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "PENDIENTE",
                            EstudianteId = 1,
                            Fecha = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PeriodoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = "PENDIENTE",
                            EstudianteId = 2,
                            Fecha = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PeriodoId = 1
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Creditos")
                        .HasColumnType("integer");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "MAT101",
                            Creditos = 15,
                            NivelId = 1,
                            Nombre = "CALCULO I"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "INF119",
                            Creditos = 20,
                            NivelId = 1,
                            Nombre = "ESTRUCTURAS DISCRETAS"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "INF110",
                            Creditos = 20,
                            NivelId = 1,
                            Nombre = "INTRODUCCION A LA INFORMATICA"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "FIS100",
                            Creditos = 15,
                            NivelId = 1,
                            Nombre = "FISICA I"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "LIN100",
                            Creditos = 15,
                            NivelId = 1,
                            Nombre = "INGLES I"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "MAT102",
                            Creditos = 20,
                            NivelId = 2,
                            Nombre = "CALCULO II"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "MAT103",
                            Creditos = 20,
                            NivelId = 2,
                            Nombre = "ALGEBRA LINEAL"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "INF120",
                            Creditos = 20,
                            NivelId = 2,
                            Nombre = "PROGRAMACION I"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "FIS102",
                            Creditos = 20,
                            NivelId = 2,
                            Nombre = "FISICA II"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "LIN101",
                            Creditos = 20,
                            NivelId = 2,
                            Nombre = "INGLES II"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "MAT207",
                            Creditos = 20,
                            NivelId = 3,
                            Nombre = "ECUACIONES DIFERENCIALES"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "INF210",
                            Creditos = 20,
                            NivelId = 3,
                            Nombre = "PROGRAMACION II"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "INF211",
                            Creditos = 20,
                            NivelId = 3,
                            Nombre = "ARQUITECTURA DE COMPUTADORAS"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "FIS200",
                            Creditos = 20,
                            NivelId = 3,
                            Nombre = "FISICA III"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "ADM100",
                            Creditos = 20,
                            NivelId = 3,
                            Nombre = "ADMINISTRACION"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "MAT202",
                            Creditos = 20,
                            NivelId = 4,
                            Nombre = "PROBABILIDAD Y ESTADISTICA I"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "MAT205",
                            Creditos = 20,
                            NivelId = 4,
                            Nombre = "METODOS NUMERICOS"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "INF220",
                            Creditos = 20,
                            NivelId = 4,
                            Nombre = "ESTRUCTURA DE DATOS I"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "INF221",
                            Creditos = 20,
                            NivelId = 4,
                            Nombre = "PROGRAMACION ENSAMBLADOR"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "ADM200",
                            Creditos = 20,
                            NivelId = 4,
                            Nombre = "CONTABILIDAD"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "MAT302",
                            Creditos = 20,
                            NivelId = 5,
                            Nombre = "PROBABILIDAD Y ESTADISTICA II"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "INF318",
                            Creditos = 20,
                            NivelId = 5,
                            Nombre = "PROGRAMACION LOGICA Y FUNCIONAL"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "INF310",
                            Creditos = 20,
                            NivelId = 5,
                            Nombre = "ESTRUCTURA DE DATOS II"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "INF312",
                            Creditos = 20,
                            NivelId = 5,
                            Nombre = "BASE DE DATOS I"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "INF319",
                            Creditos = 20,
                            NivelId = 5,
                            Nombre = "LENGUAJES FORMALES"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Niveles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "1er Semestre",
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "2do Semestre",
                            Numero = 2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "3er Semestre",
                            Numero = 3
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "4to Semestre",
                            Numero = 4
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "5to Semestre",
                            Numero = 5
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PeriodosAcademicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaFin = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gestion = "2025-1"
                        },
                        new
                        {
                            Id = 2,
                            FechaFin = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gestion = "2025-2"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanDeEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("PlanesEstudio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            Codigo = "SIS25",
                            Estado = "ACTIVO",
                            Fecha = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Plan 2025"
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 2,
                            Codigo = "IND24",
                            Estado = "ACTIVO",
                            Fecha = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Plan 2024"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PlanId", "MateriaId")
                        .IsUnique();

                    b.ToTable("PlanMaterias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MateriaId = 1,
                            PlanId = 1,
                            Semestre = 1
                        },
                        new
                        {
                            Id = 2,
                            MateriaId = 2,
                            PlanId = 1,
                            Semestre = 1
                        },
                        new
                        {
                            Id = 3,
                            MateriaId = 3,
                            PlanId = 1,
                            Semestre = 2
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Prerequisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<int>("MateriaPrerequisitoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("NotaMin")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MateriaPrerequisitoId");

                    b.HasIndex("MateriaId", "MateriaPrerequisitoId")
                        .IsUnique();

                    b.ToTable("Prerequisitos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MateriaId = 6,
                            MateriaPrerequisitoId = 1,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 2,
                            MateriaId = 7,
                            MateriaPrerequisitoId = 2,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 3,
                            MateriaId = 8,
                            MateriaPrerequisitoId = 3,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 4,
                            MateriaId = 9,
                            MateriaPrerequisitoId = 4,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 5,
                            MateriaId = 10,
                            MateriaPrerequisitoId = 5,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 6,
                            MateriaId = 11,
                            MateriaPrerequisitoId = 6,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 7,
                            MateriaId = 12,
                            MateriaPrerequisitoId = 7,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 8,
                            MateriaId = 12,
                            MateriaPrerequisitoId = 8,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 9,
                            MateriaId = 13,
                            MateriaPrerequisitoId = 8,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 10,
                            MateriaId = 13,
                            MateriaPrerequisitoId = 9,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 11,
                            MateriaId = 14,
                            MateriaPrerequisitoId = 9,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 12,
                            MateriaId = 16,
                            MateriaPrerequisitoId = 6,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 13,
                            MateriaId = 17,
                            MateriaPrerequisitoId = 11,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 14,
                            MateriaId = 18,
                            MateriaPrerequisitoId = 12,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 15,
                            MateriaId = 19,
                            MateriaPrerequisitoId = 13,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 16,
                            MateriaId = 20,
                            MateriaPrerequisitoId = 15,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 17,
                            MateriaId = 21,
                            MateriaPrerequisitoId = 16,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 18,
                            MateriaId = 22,
                            MateriaPrerequisitoId = 18,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 19,
                            MateriaId = 23,
                            MateriaPrerequisitoId = 18,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 20,
                            MateriaId = 24,
                            MateriaPrerequisitoId = 18,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        },
                        new
                        {
                            Id = 21,
                            MateriaId = 25,
                            MateriaPrerequisitoId = 18,
                            NotaMin = 51m,
                            Tipo = "OBLIGATORIO"
                        });
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.DetalleInscripcion", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.GrupoMateria", "GrupoMateria")
                        .WithMany("DetallesInscripcion")
                        .HasForeignKey("GrupoMateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAREATOPICOS.ServicioA.Models.Inscripcion", "Inscripcion")
                        .WithMany("Detalles")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMateria");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Estudiante", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.Carrera", "Carrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.GrupoMateria", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.Aula", "Aula")
                        .WithMany("Grupos")
                        .HasForeignKey("AulaId");

                    b.HasOne("TAREATOPICOS.ServicioA.Models.Docente", "Docente")
                        .WithMany("Grupos")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAREATOPICOS.ServicioA.Models.Horario", "Horario")
                        .WithMany("Grupos")
                        .HasForeignKey("HorarioId");

                    b.HasOne("TAREATOPICOS.ServicioA.Models.Materia", "Materia")
                        .WithMany("Grupos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAREATOPICOS.ServicioA.Models.PeriodoAcademico", "Periodo")
                        .WithMany("Grupos")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Docente");

                    b.Navigation("Horario");

                    b.Navigation("Materia");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.HistorialAcademico", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.DetalleInscripcion", "DetalleInscripcion")
                        .WithOne("HistorialAcademico")
                        .HasForeignKey("TAREATOPICOS.ServicioA.Models.HistorialAcademico", "DetalleInscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleInscripcion");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Inscripcion", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAREATOPICOS.ServicioA.Models.PeriodoAcademico", "Periodo")
                        .WithMany("Inscripciones")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Materia", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.Nivel", "Nivel")
                        .WithMany("Materias")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanDeEstudio", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.Carrera", "Carrera")
                        .WithMany("PlanesDeEstudio")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanMateria", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.Materia", "Materia")
                        .WithMany("PlanesMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TAREATOPICOS.ServicioA.Models.PlanDeEstudio", "Plan")
                        .WithMany("PlanesMaterias")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Prerequisito", b =>
                {
                    b.HasOne("TAREATOPICOS.ServicioA.Models.Materia", "Materia")
                        .WithMany("MateriaRequeridaPor")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TAREATOPICOS.ServicioA.Models.Materia", "MateriaPrerequisito")
                        .WithMany("RequiereMaterias")
                        .HasForeignKey("MateriaPrerequisitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("MateriaPrerequisito");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Aula", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Carrera", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("PlanesDeEstudio");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.DetalleInscripcion", b =>
                {
                    b.Navigation("HistorialAcademico");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Docente", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.GrupoMateria", b =>
                {
                    b.Navigation("DetallesInscripcion");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Horario", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Inscripcion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Materia", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("MateriaRequeridaPor");

                    b.Navigation("PlanesMaterias");

                    b.Navigation("RequiereMaterias");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.Nivel", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PeriodoAcademico", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("TAREATOPICOS.ServicioA.Models.PlanDeEstudio", b =>
                {
                    b.Navigation("PlanesMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
