CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Aulas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text NOT NULL,
    "Capacidad" integer NOT NULL,
    "Ubicacion" text NOT NULL,
    CONSTRAINT "PK_Aulas" PRIMARY KEY ("Id")
);

CREATE TABLE "Carreras" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Carreras" PRIMARY KEY ("Id")
);

CREATE TABLE "Docentes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Registro" text NOT NULL,
    "Ci" text NOT NULL,
    "Nombre" text NOT NULL,
    "Telefono" text,
    "Estado" text NOT NULL,
    CONSTRAINT "PK_Docentes" PRIMARY KEY ("Id")
);

CREATE TABLE "Horarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Dia" text NOT NULL,
    "HoraInicio" time without time zone NOT NULL,
    "HoraFin" time without time zone NOT NULL,
    CONSTRAINT "PK_Horarios" PRIMARY KEY ("Id")
);

CREATE TABLE "Niveles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Numero" integer NOT NULL,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Niveles" PRIMARY KEY ("Id")
);

CREATE TABLE "PeriodosAcademicos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Gestion" text NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PeriodosAcademicos" PRIMARY KEY ("Id")
);

CREATE TABLE "ProcessedMessages" (
    "MessageId" uuid NOT NULL,
    "ProcessedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProcessedMessages" PRIMARY KEY ("MessageId")
);

CREATE TABLE "Transacciones" (
    "Id" uuid NOT NULL,
    "TipoOperacion" text NOT NULL,
    "Entidad" text NOT NULL,
    "Payload" text,
    "Estado" text NOT NULL,
    "Attempt" integer NOT NULL,
    "Priority" integer NOT NULL,
    "MaxRetries" integer NOT NULL,
    "CallbackUrl" text,
    "CallbackSecret" text,
    "IdempotencyKey" text,
    "NotBefore" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Transacciones" PRIMARY KEY ("Id")
);

CREATE TABLE "Estudiantes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Registro" text NOT NULL,
    "Ci" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Nombre" text NOT NULL,
    "Email" text NOT NULL,
    "Telefono" text,
    "Direccion" text,
    "Estado" text NOT NULL,
    "CarreraId" integer NOT NULL,
    CONSTRAINT "PK_Estudiantes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Estudiantes_Carreras_CarreraId" FOREIGN KEY ("CarreraId") REFERENCES "Carreras" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PlanesEstudio" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Codigo" text,
    "Fecha" timestamp with time zone NOT NULL,
    "Estado" text NOT NULL,
    "CarreraId" integer NOT NULL,
    CONSTRAINT "PK_PlanesEstudio" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlanesEstudio_Carreras_CarreraId" FOREIGN KEY ("CarreraId") REFERENCES "Carreras" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Materias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text NOT NULL,
    "Nombre" text NOT NULL,
    "Creditos" integer NOT NULL,
    "NivelId" integer NOT NULL,
    CONSTRAINT "PK_Materias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Materias_Niveles_NivelId" FOREIGN KEY ("NivelId") REFERENCES "Niveles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Inscripciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Fecha" timestamp with time zone NOT NULL,
    "Estado" text NOT NULL,
    "EstudianteId" integer NOT NULL,
    "PeriodoId" integer NOT NULL,
    CONSTRAINT "PK_Inscripciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Inscripciones_Estudiantes_EstudianteId" FOREIGN KEY ("EstudianteId") REFERENCES "Estudiantes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Inscripciones_PeriodosAcademicos_PeriodoId" FOREIGN KEY ("PeriodoId") REFERENCES "PeriodosAcademicos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GruposMaterias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Grupo" text NOT NULL,
    "Cupo" integer NOT NULL DEFAULT 0,
    "Estado" text NOT NULL,
    "MateriaId" integer NOT NULL,
    "DocenteId" integer NOT NULL,
    "PeriodoId" integer NOT NULL,
    "HorarioId" integer,
    "AulaId" integer,
    CONSTRAINT "PK_GruposMaterias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GruposMaterias_Aulas_AulaId" FOREIGN KEY ("AulaId") REFERENCES "Aulas" ("Id"),
    CONSTRAINT "FK_GruposMaterias_Docentes_DocenteId" FOREIGN KEY ("DocenteId") REFERENCES "Docentes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GruposMaterias_Horarios_HorarioId" FOREIGN KEY ("HorarioId") REFERENCES "Horarios" ("Id"),
    CONSTRAINT "FK_GruposMaterias_Materias_MateriaId" FOREIGN KEY ("MateriaId") REFERENCES "Materias" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GruposMaterias_PeriodosAcademicos_PeriodoId" FOREIGN KEY ("PeriodoId") REFERENCES "PeriodosAcademicos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PlanMaterias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlanId" integer NOT NULL,
    "MateriaId" integer NOT NULL,
    "Semestre" integer NOT NULL,
    CONSTRAINT "PK_PlanMaterias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlanMaterias_Materias_MateriaId" FOREIGN KEY ("MateriaId") REFERENCES "Materias" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlanMaterias_PlanesEstudio_PlanId" FOREIGN KEY ("PlanId") REFERENCES "PlanesEstudio" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Prerequisitos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Tipo" text NOT NULL,
    "NotaMin" numeric NOT NULL,
    "MateriaId" integer NOT NULL,
    "MateriaPrerequisitoId" integer NOT NULL,
    CONSTRAINT "PK_Prerequisitos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Prerequisitos_Materias_MateriaId" FOREIGN KEY ("MateriaId") REFERENCES "Materias" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prerequisitos_Materias_MateriaPrerequisitoId" FOREIGN KEY ("MateriaPrerequisitoId") REFERENCES "Materias" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "DetallesInscripciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text NOT NULL,
    "Estado" text NOT NULL,
    "NotaFinal" integer,
    "InscripcionId" integer NOT NULL,
    "GrupoMateriaId" integer NOT NULL,
    CONSTRAINT "PK_DetallesInscripciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DetallesInscripciones_GruposMaterias_GrupoMateriaId" FOREIGN KEY ("GrupoMateriaId") REFERENCES "GruposMaterias" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DetallesInscripciones_Inscripciones_InscripcionId" FOREIGN KEY ("InscripcionId") REFERENCES "Inscripciones" ("Id") ON DELETE CASCADE
);

CREATE TABLE "HistorialesAcademicos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Intento" integer NOT NULL,
    "UltimaNota" numeric,
    "Aprobado" boolean NOT NULL,
    "FechaAprobacion" timestamp with time zone,
    "DetalleInscripcionId" integer NOT NULL,
    CONSTRAINT "PK_HistorialesAcademicos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistorialesAcademicos_DetallesInscripciones_DetalleInscripc~" FOREIGN KEY ("DetalleInscripcionId") REFERENCES "DetallesInscripciones" ("Id") ON DELETE CASCADE
);

INSERT INTO "Aulas" ("Id", "Capacidad", "Codigo", "Ubicacion")
VALUES (1, 40, 'A101', 'Bloque A');
INSERT INTO "Aulas" ("Id", "Capacidad", "Codigo", "Ubicacion")
VALUES (2, 35, 'B201', 'Bloque B');
INSERT INTO "Aulas" ("Id", "Capacidad", "Codigo", "Ubicacion")
VALUES (3, 50, 'C301', 'Bloque C');

INSERT INTO "Carreras" ("Id", "Nombre")
VALUES (1, 'Ingeniería de Sistemas');
INSERT INTO "Carreras" ("Id", "Nombre")
VALUES (2, 'Ingeniería Industrial');
INSERT INTO "Carreras" ("Id", "Nombre")
VALUES (3, 'Administración de Empresas');

INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (1, '123456', 'ACTIVO', 'ABARCA SOTA NANCY', 'DOC001', '70000001');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (2, '123457', 'ACTIVO', 'ACOSTA CABEZAS BARTOLO JAVIER', 'DOC002', '70000002');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (3, '123458', 'ACTIVO', 'AGUILAR MARTINEZ DOMINGO', 'DOC003', '70000003');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (4, '123459', 'ACTIVO', 'ALIAGA HOWARD SHARON KENNY', 'DOC004', '70000004');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (5, '123460', 'ACTIVO', 'ALPIRE RIVERO GERMAN', 'DOC005', '70000005');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (6, '123461', 'ACTIVO', 'ARANIBAR QUIROZ M. MONICA', 'DOC006', '70000006');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (7, '123462', 'ACTIVO', 'ARGOTE CLAROS IRMA ISABEL', 'DOC007', '70000007');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (8, '123463', 'ACTIVO', 'ATILA LIJERON JHONNY DAVID', 'DOC008', '70000008');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (9, '123464', 'ACTIVO', 'AVENDAÑO GONZALES EUDAL', 'DOC009', '70000009');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (10, '123465', 'ACTIVO', 'BALCAZAR VEIZAGA EVANS', 'DOC010', '70000010');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (11, '123466', 'ACTIVO', 'BARROSO VIRUEZ GINO', 'DOC011', '70000011');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (12, '123467', 'ACTIVO', 'CABALLERO RUA MAURICIO CHRISTI', 'DOC012', '70000012');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (13, '123468', 'ACTIVO', 'CABELLO MERIDA JUAN RUBEN', 'DOC013', '70000013');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (14, '123469', 'ACTIVO', 'CACERES CHACON BRAULIO', 'DOC014', '70000014');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (15, '123470', 'ACTIVO', 'CALDERON FLORES MODESTO FRANK', 'DOC015', '70000015');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (16, '123471', 'ACTIVO', 'CALIZAYA AJHUACHO MAGNO EDWIN', 'DOC016', '70000016');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (17, '123472', 'ACTIVO', 'CALLE TERRAZAS EDWIN', 'DOC017', '70000017');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (18, '123473', 'ACTIVO', 'CAMPOS BARRERA MARIO', 'DOC018', '70000018');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (19, '123474', 'ACTIVO', 'CANO CESPEDES JORGE', 'DOC019', '70000019');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (20, '123475', 'ACTIVO', 'CARVAJAL CORDERO MARCIO', 'DOC020', '70000020');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (21, '123476', 'ACTIVO', 'CARRENO PEREIRA ANDRES', 'DOC021', '70000021');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (22, '123477', 'ACTIVO', 'CASTRO MARISCAL JHONNY', 'DOC022', '70000022');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (23, '123478', 'ACTIVO', 'CAYOJA LUCANA VICTOR MILTON', 'DOC023', '70000023');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (24, '123479', 'ACTIVO', 'CHAHIN AVICHACRA JUAN MANUEL', 'DOC024', '70000024');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (25, '123480', 'ACTIVO', 'CHAU WONG JORGE', 'DOC025', '70000025');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (26, '123481', 'ACTIVO', 'CLAURE MEDRANO DE OROPEZA ELIZ', 'DOC026', '70000026');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (27, '123482', 'ACTIVO', 'CONTRERAS VILLEGAS JUAN CARLOS', 'DOC027', '70000027');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (28, '123483', 'ACTIVO', 'CORTEZ UZEDA JULIO MARTIN', 'DOC028', '70000028');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (29, '123484', 'ACTIVO', 'DAVALOS SANCHEZ DE MANCILLA Pl', 'DOC029', '70000029');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (30, '123485', 'ACTIVO', 'DURAN CESPEDES BERTHY RONALD', 'DOC030', '70000030');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (31, '123486', 'ACTIVO', 'EVELYN VANESA SORIA AVILA', 'DOC031', '70000031');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (32, '123487', 'ACTIVO', 'FLORES CUELLAD DAVID LUIS', 'DOC032', '70000032');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (33, '123488', 'ACTIVO', 'FLORES FLORES MARCOS OSCAR', 'DOC033', '70000033');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (34, '123489', 'ACTIVO', 'FLORES GUZMAN VALENTIN VICTOR', 'DOC034', '70000034');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (35, '123490', 'ACTIVO', 'GARZON CUELLAR ANGELICA', 'DOC035', '70000035');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (36, '123491', 'ACTIVO', 'GIANELLA PEREDO EDUARDO', 'DOC036', '70000036');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (37, '123492', 'ACTIVO', 'GIANELLA PEREDO LUIS ANTONIO', 'DOC037', '70000037');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (38, '123493', 'ACTIVO', 'GONZALES SANDOVAL JORGE ANTONI', 'DOC038', '70000038');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (39, '123494', 'ACTIVO', 'GRAGEDA ESCUDERO MARIO WILSON', 'DOC039', '70000039');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (40, '123495', 'ACTIVO', 'GRIMALDO BRAVO PAUL', 'DOC040', '70000040');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (41, '123496', 'ACTIVO', 'GUARACHI SOLANO JONATHAN FELIX', 'DOC041', '70000041');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (42, '123497', 'ACTIVO', 'GUTHRIE PACHECO MIGUEL ANGEL', 'DOC042', '70000042');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (43, '123498', 'ACTIVO', 'GUTIERREZ BRUNO KATIME ESTHER', 'DOC043', '70000043');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (44, '123499', 'ACTIVO', 'HINOJOSA SAAVEDRA JOSE SAID', 'DOC044', '70000044');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (45, '123500', 'ACTIVO', 'JUSTINIANO FLORES CARMEN LILIA', 'DOC045', '70000045');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (46, '123501', 'ACTIVO', 'JUSTINIANO ROCA RONALD', 'DOC046', '70000046');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (47, '123502', 'ACTIVO', 'JUSTINIANO VACA JUAN TOMAS', 'DOC047', '70000047');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (48, '123503', 'ACTIVO', 'LAMAS RODRIGUEZ MARCOS', 'DOC048', '70000048');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (49, '123504', 'ACTIVO', 'LAZO ARTEAGA CARLOS ROBERTO', 'DOC049', '70000049');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (50, '123505', 'ACTIVO', 'LAZO QUISPE SEBASTIAN', 'DOC050', '70000050');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (51, '123506', 'ACTIVO', 'LOBO LIMPIAS VICTOR HUGO', 'DOC051', '70000051');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (52, '123507', 'ACTIVO', 'LOPEZ NEGRETTY MARY DUNNIA', 'DOC052', '70000052');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (53, '123508', 'ACTIVO', 'LOPEZ WINNIPEG MARIO MILTON', 'DOC053', '70000053');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (54, '123509', 'ACTIVO', 'MARTINEZ CANEDO ROLANDO ANTONI', 'DOC054', '70000054');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (55, '123510', 'ACTIVO', 'MARTINEZ CARDONA SARAH MIRNA', 'DOC055', '70000055');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (56, '123511', 'ACTIVO', 'MIRANDA CARRASCO CARLOS', 'DOC056', '70000056');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (57, '123512', 'ACTIVO', 'MOLLO MAMANI ALBERTO', 'DOC057', '70000057');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (58, '123513', 'ACTIVO', 'MONRROY DIPP VICTOR FERNANDO', 'DOC058', '70000058');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (59, '123514', 'ACTIVO', 'MORALES MENDEZ MAGALY', 'DOC059', '70000059');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (60, '123515', 'ACTIVO', 'MORENO SUAREZ ENRIQUE', 'DOC060', '70000060');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (61, '123516', 'ACTIVO', 'OQUENDO HEREDIA FREDDY MIGUEL', 'DOC061', '70000061');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (62, '123517', 'ACTIVO', 'ORNOSCO GOMEZ RUBEN', 'DOC062', '70000062');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (63, '123518', 'ACTIVO', 'ORTIZ ARTEAGA VICTOR HUGO', 'DOC063', '70000063');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (64, '123519', 'ACTIVO', 'OROPEZA CLAURE GUSTAVO ADOLFO', 'DOC064', '70000064');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (65, '123520', 'ACTIVO', 'PEINADO PEREIRA JUAN CARLOS', 'DOC065', '70000065');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (66, '123521', 'ACTIVO', 'PEINADO PEREIRA MIGUEL JESUS', 'DOC066', '70000066');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (67, '123522', 'ACTIVO', 'PEREZ DELGADILLO SHIRLEY EULAL', 'DOC067', '70000067');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (68, '123523', 'ACTIVO', 'PEREZ FERREIRA UBALDO', 'DOC068', '70000068');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (69, '123524', 'ACTIVO', 'PINTO VARGAS EDUARDO', 'DOC069', '70000069');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (70, '123525', 'ACTIVO', 'POR DESIGNAR', 'DOC070', '70000070');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (71, '123526', 'ACTIVO', 'RISSIOTTI VELASQUEZ EDGAR ZACA', 'DOC071', '70000071');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (72, '123527', 'ACTIVO', 'ROCHA ARGOTE FERNANDO', 'DOC072', '70000072');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (73, '123528', 'ACTIVO', 'ROMAN ROCA RUFINO WILBERTO', 'DOC073', '70000073');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (74, '123529', 'ACTIVO', 'ROSALES FUENTES JORGE MARCELO', 'DOC074', '70000074');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (75, '123530', 'ACTIVO', 'SALVATIERRA MERCADO ROLANDO', 'DOC075', '70000075');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (76, '123531', 'ACTIVO', 'SANCHEZ RIOJA EDWIN ALEJANDRO', 'DOC076', '70000076');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (77, '123532', 'ACTIVO', 'SANCHEZ VELASCO ENRIQUE', 'DOC077', '70000077');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (78, '123533', 'ACTIVO', 'SELAYA GARVIZU IVAN VLADISHLAV', 'DOC078', '70000078');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (79, '123534', 'ACTIVO', 'SEVERICHE TOLEDO SAUL', 'DOC079', '70000079');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (80, '123535', 'ACTIVO', 'SILES MUÑOZ FELIX', 'DOC080', '70000080');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (81, '123536', 'ACTIVO', 'SUAREZ CESPEDES MELBY', 'DOC081', '70000081');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (82, '123537', 'ACTIVO', 'TAPIA FLORES LUIS PERCY', 'DOC082', '70000082');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (83, '123538', 'ACTIVO', 'TEJERINA GUERRA JULIO', 'DOC083', '70000083');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (84, '123539', 'ACTIVO', 'TERRAZAS SOTO RICARDO', 'DOC084', '70000084');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (85, '123540', 'ACTIVO', 'TORREZ CAMACHO LUZ DIANA', 'DOC085', '70000085');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (86, '123541', 'ACTIVO', 'VACA PINTO CESPEDES ROBERTO CA', 'DOC086', '70000086');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (87, '123542', 'ACTIVO', 'VALDELOMAR ORELLANA TOMAS', 'DOC087', '70000087');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (88, '123543', 'ACTIVO', 'VALLET VALLET CORRADO', 'DOC088', '70000088');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (89, '123544', 'ACTIVO', 'VARGAS CASTILLO CIRO EDGAR', 'DOC089', '70000089');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (90, '123545', 'ACTIVO', 'VARGAS PEÑA LEONARDO', 'DOC090', '70000090');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (91, '123546', 'ACTIVO', 'VARGAS YAPURA EDWIN', 'DOC091', '70000091');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (92, '123547', 'ACTIVO', 'VEIZAGA GONZALES JOSUE OBED', 'DOC092', '70000092');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (93, '123548', 'ACTIVO', 'VELASCO GUAMAN ANGEL', 'DOC093', '70000093');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (94, '123549', 'ACTIVO', 'VILLAGOMEZ MELGAR JOSE JUNIOR', 'DOC094', '70000094');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (95, '123550', 'ACTIVO', 'ZEBALLOS PAREDES DANIEL LUIS', 'DOC095', '70000095');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (96, '123551', 'ACTIVO', 'ZUNA VILLAGOMEZ JULIO', 'DOC096', '70000096');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (97, '123552', 'ACTIVO', 'ZUNA VILLAGOMEZ RICARDO', 'DOC097', '70000097');
INSERT INTO "Docentes" ("Id", "Ci", "Estado", "Nombre", "Registro", "Telefono")
VALUES (98, '123553', 'ACTIVO', 'ZUÑIGA RUIZ WILMA', 'DOC098', '70000098');

INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (1, 'Mar-Jue', TIME '20:30:00', TIME '18:15:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (2, 'Mar-Jue', TIME '09:15:00', TIME '07:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (3, 'Mar-Jue', TIME '10:00:00', TIME '08:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (4, 'Mar-Jue', TIME '10:00:00', TIME '08:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (5, 'Mar-Jue', TIME '10:00:00', TIME '08:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (6, 'Mar-Jue', TIME '10:00:00', TIME '08:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (7, 'Mar-Jue', TIME '10:00:00', TIME '08:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (8, 'Mar-Jue', TIME '10:00:00', TIME '08:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (9, 'Mar-Jue', TIME '10:00:00', TIME '08:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (10, 'Lun-Mie-Vie', TIME '10:00:00', TIME '08:30:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (11, 'Lun-Mie-Vie', TIME '11:30:00', TIME '10:00:00');
INSERT INTO "Horarios" ("Id", "Dia", "HoraFin", "HoraInicio")
VALUES (12, 'Lun-Mie-Vie', TIME '08:30:00', TIME '07:00:00');

INSERT INTO "Niveles" ("Id", "Nombre", "Numero")
VALUES (1, '1er Semestre', 1);
INSERT INTO "Niveles" ("Id", "Nombre", "Numero")
VALUES (2, '2do Semestre', 2);
INSERT INTO "Niveles" ("Id", "Nombre", "Numero")
VALUES (3, '3er Semestre', 3);
INSERT INTO "Niveles" ("Id", "Nombre", "Numero")
VALUES (4, '4to Semestre', 4);
INSERT INTO "Niveles" ("Id", "Nombre", "Numero")
VALUES (5, '5to Semestre', 5);

INSERT INTO "PeriodosAcademicos" ("Id", "FechaFin", "FechaInicio", "Gestion")
VALUES (1, TIMESTAMPTZ '2025-06-30T00:00:00Z', TIMESTAMPTZ '2025-02-01T00:00:00Z', '2025-1');
INSERT INTO "PeriodosAcademicos" ("Id", "FechaFin", "FechaInicio", "Gestion")
VALUES (2, TIMESTAMPTZ '2025-12-15T00:00:00Z', TIMESTAMPTZ '2025-08-01T00:00:00Z', '2025-2');

INSERT INTO "Estudiantes" ("Id", "CarreraId", "Ci", "Direccion", "Email", "Estado", "Nombre", "PasswordHash", "Registro", "Telefono")
VALUES (1, 1, '7894561', NULL, 'carlos@uni.edu', 'ACTIVO', 'Carlos Sánchez', '$2a$11$YP4gNElOt/d79qZIHbwT3eAxgSg8R.DkDofhZOnq2dH1/IytjKdSq', '20251234', NULL);
INSERT INTO "Estudiantes" ("Id", "CarreraId", "Ci", "Direccion", "Email", "Estado", "Nombre", "PasswordHash", "Registro", "Telefono")
VALUES (2, 2, '222222', NULL, 'ana@uni.edu', 'ACTIVO', 'Ana Rodríguez', '$2a$11$YP4gNElOt/d79qZIHbwT3eAxgSg8R.DkDofhZOnq2dH1/IytjKdSq', 'EST002', NULL);

INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (1, 'MAT101', 15, 1, 'CALCULO I');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (2, 'INF119', 20, 1, 'ESTRUCTURAS DISCRETAS');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (3, 'INF110', 20, 1, 'INTRODUCCION A LA INFORMATICA');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (4, 'FIS100', 15, 1, 'FISICA I');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (5, 'LIN100', 15, 1, 'INGLES I');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (6, 'MAT102', 20, 2, 'CALCULO II');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (7, 'MAT103', 20, 2, 'ALGEBRA LINEAL');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (8, 'INF120', 20, 2, 'PROGRAMACION I');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (9, 'FIS102', 20, 2, 'FISICA II');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (10, 'LIN101', 20, 2, 'INGLES II');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (11, 'MAT207', 20, 3, 'ECUACIONES DIFERENCIALES');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (12, 'INF210', 20, 3, 'PROGRAMACION II');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (13, 'INF211', 20, 3, 'ARQUITECTURA DE COMPUTADORAS');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (14, 'FIS200', 20, 3, 'FISICA III');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (15, 'ADM100', 20, 3, 'ADMINISTRACION');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (16, 'MAT202', 20, 4, 'PROBABILIDAD Y ESTADISTICA I');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (17, 'MAT205', 20, 4, 'METODOS NUMERICOS');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (18, 'INF220', 20, 4, 'ESTRUCTURA DE DATOS I');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (19, 'INF221', 20, 4, 'PROGRAMACION ENSAMBLADOR');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (20, 'ADM200', 20, 4, 'CONTABILIDAD');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (21, 'MAT302', 20, 5, 'PROBABILIDAD Y ESTADISTICA II');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (22, 'INF318', 20, 5, 'PROGRAMACION LOGICA Y FUNCIONAL');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (23, 'INF310', 20, 5, 'ESTRUCTURA DE DATOS II');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (24, 'INF312', 20, 5, 'BASE DE DATOS I');
INSERT INTO "Materias" ("Id", "Codigo", "Creditos", "NivelId", "Nombre")
VALUES (25, 'INF319', 20, 5, 'LENGUAJES FORMALES');

INSERT INTO "PlanesEstudio" ("Id", "CarreraId", "Codigo", "Estado", "Fecha", "Nombre")
VALUES (1, 1, 'SIS25', 'ACTIVO', TIMESTAMPTZ '2025-01-01T00:00:00Z', 'Plan 2025');
INSERT INTO "PlanesEstudio" ("Id", "CarreraId", "Codigo", "Estado", "Fecha", "Nombre")
VALUES (2, 2, 'IND24', 'ACTIVO', TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Plan 2024');

INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (1, 1, 1, 97, 'ACTIVO', 'SB', 11, 3, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (2, 1, 1, 57, 'ACTIVO', 'SD', 1, 3, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (3, 1, 5, 35, 'ACTIVO', 'SF', 10, 3, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (4, 1, 5, 92, 'ACTIVO', 'Z1', 12, 3, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (5, 1, 1, 55, 'ACTIVO', 'SF', 12, 2, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (6, 2, 1, 56, 'ACTIVO', 'SH', 2, 2, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (7, 2, 5, 43, 'ACTIVO', 'SK', 2, 2, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (8, 2, 5, 14, 'ACTIVO', 'Z2', 10, 2, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (9, 2, 1, 9, 'ACTIVO', 'F1', 10, 1, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (10, 2, 1, 16, 'ACTIVO', 'SG', 10, 1, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (11, 2, 5, 80, 'ACTIVO', 'Z1', 10, 1, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (12, 2, 1, 26, 'ACTIVO', 'Z1', 10, 5, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (13, 2, 5, 98, 'ACTIVO', 'Z3', 10, 5, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (14, 2, 1, 63, 'ACTIVO', 'Z1', 10, 4, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (15, 2, 5, 25, 'ACTIVO', 'Z3', 10, 4, 1);
INSERT INTO "GruposMaterias" ("Id", "AulaId", "Cupo", "DocenteId", "Estado", "Grupo", "HorarioId", "MateriaId", "PeriodoId")
VALUES (16, 2, 5, 23, 'ACTIVO', 'SI', 10, 4, 1);

INSERT INTO "Inscripciones" ("Id", "Estado", "EstudianteId", "Fecha", "PeriodoId")
VALUES (1, 'PENDIENTE', 1, TIMESTAMPTZ '2025-02-05T00:00:00Z', 1);
INSERT INTO "Inscripciones" ("Id", "Estado", "EstudianteId", "Fecha", "PeriodoId")
VALUES (2, 'PENDIENTE', 2, TIMESTAMPTZ '2025-02-06T00:00:00Z', 1);

INSERT INTO "PlanMaterias" ("Id", "MateriaId", "PlanId", "Semestre")
VALUES (1, 1, 1, 1);
INSERT INTO "PlanMaterias" ("Id", "MateriaId", "PlanId", "Semestre")
VALUES (2, 2, 1, 1);
INSERT INTO "PlanMaterias" ("Id", "MateriaId", "PlanId", "Semestre")
VALUES (3, 3, 1, 1);
INSERT INTO "PlanMaterias" ("Id", "MateriaId", "PlanId", "Semestre")
VALUES (4, 4, 1, 1);
INSERT INTO "PlanMaterias" ("Id", "MateriaId", "PlanId", "Semestre")
VALUES (5, 5, 1, 1);
INSERT INTO "PlanMaterias" ("Id", "MateriaId", "PlanId", "Semestre")
VALUES (6, 3, 1, 2);

INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (1, 6, 1, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (2, 7, 2, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (3, 8, 3, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (4, 9, 4, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (5, 10, 5, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (6, 11, 6, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (7, 12, 7, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (8, 12, 8, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (9, 13, 8, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (10, 13, 9, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (11, 14, 9, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (12, 16, 6, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (13, 17, 11, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (14, 18, 12, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (15, 19, 13, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (16, 20, 15, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (17, 21, 16, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (18, 22, 18, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (19, 23, 18, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (20, 24, 18, 51.0, 'OBLIGATORIO');
INSERT INTO "Prerequisitos" ("Id", "MateriaId", "MateriaPrerequisitoId", "NotaMin", "Tipo")
VALUES (21, 25, 18, 51.0, 'OBLIGATORIO');

INSERT INTO "DetallesInscripciones" ("Id", "Codigo", "Estado", "GrupoMateriaId", "InscripcionId", "NotaFinal")
VALUES (1, 'DET001', 'INSCRITO', 1, 1, NULL);
INSERT INTO "DetallesInscripciones" ("Id", "Codigo", "Estado", "GrupoMateriaId", "InscripcionId", "NotaFinal")
VALUES (2, 'DET002', 'INSCRITO', 2, 2, NULL);

INSERT INTO "HistorialesAcademicos" ("Id", "Aprobado", "DetalleInscripcionId", "FechaAprobacion", "Intento", "UltimaNota")
VALUES (1, TRUE, 1, TIMESTAMPTZ '2025-06-30T00:00:00Z', 1, 85.0);
INSERT INTO "HistorialesAcademicos" ("Id", "Aprobado", "DetalleInscripcionId", "FechaAprobacion", "Intento", "UltimaNota")
VALUES (2, FALSE, 2, TIMESTAMPTZ '2025-06-30T00:00:00Z', 1, 70.0);

CREATE UNIQUE INDEX "IX_Aulas_Codigo" ON "Aulas" ("Codigo");

CREATE INDEX "IX_DetallesInscripciones_GrupoMateriaId" ON "DetallesInscripciones" ("GrupoMateriaId");

CREATE UNIQUE INDEX "IX_DetallesInscripciones_InscripcionId_GrupoMateriaId" ON "DetallesInscripciones" ("InscripcionId", "GrupoMateriaId");

CREATE INDEX "IX_Estudiantes_CarreraId" ON "Estudiantes" ("CarreraId");

CREATE UNIQUE INDEX "IX_Estudiantes_Registro" ON "Estudiantes" ("Registro");

CREATE INDEX "IX_GruposMaterias_AulaId" ON "GruposMaterias" ("AulaId");

CREATE INDEX "IX_GruposMaterias_DocenteId" ON "GruposMaterias" ("DocenteId");

CREATE INDEX "IX_GruposMaterias_HorarioId" ON "GruposMaterias" ("HorarioId");

CREATE INDEX "IX_GruposMaterias_MateriaId" ON "GruposMaterias" ("MateriaId");

CREATE INDEX "IX_GruposMaterias_PeriodoId" ON "GruposMaterias" ("PeriodoId");

CREATE UNIQUE INDEX "IX_HistorialesAcademicos_DetalleInscripcionId" ON "HistorialesAcademicos" ("DetalleInscripcionId");

CREATE INDEX "IX_Inscripciones_EstudianteId" ON "Inscripciones" ("EstudianteId");

CREATE INDEX "IX_Inscripciones_PeriodoId" ON "Inscripciones" ("PeriodoId");

CREATE UNIQUE INDEX "IX_Materias_Codigo" ON "Materias" ("Codigo");

CREATE INDEX "IX_Materias_NivelId" ON "Materias" ("NivelId");

CREATE UNIQUE INDEX "IX_Niveles_Numero" ON "Niveles" ("Numero");

CREATE UNIQUE INDEX "IX_PeriodosAcademicos_Gestion" ON "PeriodosAcademicos" ("Gestion");

CREATE INDEX "IX_PlanesEstudio_CarreraId" ON "PlanesEstudio" ("CarreraId");

CREATE UNIQUE INDEX "IX_PlanesEstudio_Codigo" ON "PlanesEstudio" ("Codigo");

CREATE INDEX "IX_PlanMaterias_MateriaId" ON "PlanMaterias" ("MateriaId");

CREATE UNIQUE INDEX "IX_PlanMaterias_PlanId_MateriaId" ON "PlanMaterias" ("PlanId", "MateriaId");

CREATE UNIQUE INDEX "IX_Prerequisitos_MateriaId_MateriaPrerequisitoId" ON "Prerequisitos" ("MateriaId", "MateriaPrerequisitoId");

CREATE INDEX "IX_Prerequisitos_MateriaPrerequisitoId" ON "Prerequisitos" ("MateriaPrerequisitoId");

SELECT setval(
    pg_get_serial_sequence('"Aulas"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Aulas") + 1,
        nextval(pg_get_serial_sequence('"Aulas"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Carreras"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Carreras") + 1,
        nextval(pg_get_serial_sequence('"Carreras"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Docentes"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Docentes") + 1,
        nextval(pg_get_serial_sequence('"Docentes"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Horarios"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Horarios") + 1,
        nextval(pg_get_serial_sequence('"Horarios"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Niveles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Niveles") + 1,
        nextval(pg_get_serial_sequence('"Niveles"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"PeriodosAcademicos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "PeriodosAcademicos") + 1,
        nextval(pg_get_serial_sequence('"PeriodosAcademicos"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Estudiantes"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Estudiantes") + 1,
        nextval(pg_get_serial_sequence('"Estudiantes"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Materias"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Materias") + 1,
        nextval(pg_get_serial_sequence('"Materias"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"PlanesEstudio"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "PlanesEstudio") + 1,
        nextval(pg_get_serial_sequence('"PlanesEstudio"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"GruposMaterias"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "GruposMaterias") + 1,
        nextval(pg_get_serial_sequence('"GruposMaterias"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Inscripciones"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Inscripciones") + 1,
        nextval(pg_get_serial_sequence('"Inscripciones"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"PlanMaterias"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "PlanMaterias") + 1,
        nextval(pg_get_serial_sequence('"PlanMaterias"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Prerequisitos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Prerequisitos") + 1,
        nextval(pg_get_serial_sequence('"Prerequisitos"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"DetallesInscripciones"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "DetallesInscripciones") + 1,
        nextval(pg_get_serial_sequence('"DetallesInscripciones"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"HistorialesAcademicos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "HistorialesAcademicos") + 1,
        nextval(pg_get_serial_sequence('"HistorialesAcademicos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251015134725_InitialCreate', '9.0.8');

COMMIT;

