apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: 693488589721.dkr.ecr.us-east-2.amazonaws.com/apigateway:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: LoadBalancer   # <- esto le da IP pública en AWS
  selector:
    app: apigateway
  ports:
    - port: 80
      targetPort: 5000
