apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviciob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviciob
  template:
    metadata:
      labels:
        app: serviciob
    spec:
      containers:
        - name: serviciob
          image: 693488589721.dkr.ecr.us-east-2.amazonaws.com/serviciob:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: serviciob
spec:
  selector:
    app: serviciob
  ports:
    - port: 5000
      targetPort: 5000
